version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: fp-blog
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: fp_blog
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: fp_blog
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379

